spring:
  application:
    name: spring-data-jpa-homework

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/spring_data_jpa_homework_db
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
